name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
    id-token: write # 👈 required for OIDC
    contents: read

    defaults:
      run:
        working-directory: webapp/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Lambda package
        run: zip -r code.zip .

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::223133989000:role/github-action-role
          aws-region: eu-north-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-north-1:223133989000:function:TestFunction \
            --zip-file fileb://code.zip
